export const presets = [
  {
    name: 'Starfield',
    icon: '⭐',
    config: {
      particleCount: 300,
      speed: 0.5,
      size: 2,
      gravity: 0,
      trailLength: 0.1,
      mouseForce: 0.3,
      mouseRadius: 150,
      connectionDistance: 100,
      colorOffset: 200,
      saturation: 80,
      lightness: 70,
      mouseInteraction: true,
      showConnections: true,
    },
  },
  {
    name: 'Fireworks',
    icon: '🎆',
    config: {
      particleCount: 500,
      speed: 3,
      size: 3,
      gravity: 0.1,
      trailLength: 0.8,
      mouseForce: 0,
      mouseRadius: 100,
      connectionDistance: 0,
      colorOffset: 0,
      saturation: 100,
      lightness: 60,
      mouseInteraction: false,
      showConnections: false,
    },
  },
  {
    name: 'Aurora',
    icon: '🌌',
    config: {
      particleCount: 400,
      speed: 0.3,
      size: 4,
      gravity: -0.02,
      trailLength: 0.9,
      mouseForce: 0.2,
      mouseRadius: 200,
      connectionDistance: 80,
      colorOffset: 150,
      saturation: 70,
      lightness: 50,
      mouseInteraction: true,
      showConnections: true,
    },
  },
  {
    name: 'Black Hole',
    icon: '🌀',
    config: {
      particleCount: 600,
      speed: 2,
      size: 2,
      gravity: 0,
      trailLength: 0.7,
      mouseForce: -0.8,
      mouseRadius: 250,
      connectionDistance: 50,
      colorOffset: 280,
      saturation: 90,
      lightness: 60,
      mouseInteraction: true,
      showConnections: true,
    },
  },
  {
    name: 'Snow',
    icon: '❄️',
    config: {
      particleCount: 400,
      speed: 0.5,
      size: 3,
      gravity: 0.05,
      trailLength: 0.3,
      mouseForce: 0.5,
      mouseRadius: 150,
      connectionDistance: 0,
      colorOffset: 200,
      saturation: 20,
      lightness: 90,
      mouseInteraction: true,
      showConnections: false,
    },
  },
  {
    name: 'Galaxy',
    icon: '🌠',
    config: {
      particleCount: 700,
      speed: 1.5,
      size: 2.5,
      gravity: -0.01,
      trailLength: 0.85,
      mouseForce: 0.4,
      mouseRadius: 200,
      connectionDistance: 70,
      colorOffset: 250,
      saturation: 85,
      lightness: 65,
      mouseInteraction: true,
      showConnections: true,
    },
  },
];